version: '3.9'

services:
  backend:
    container_name: 'kpd-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 4000:3000
    networks:
      - backend-db
    depends_on:
      - database

  frontend:
    container_name: 'kpd-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80

  database:
    container_name: 'kpd-database'
    image: postgres:12.12-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_PGDATA}
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend-db

volumes:
  postgres_data:
    driver: local

networks:
  frontend: {}
  backend-db: {}
